# Generated by Django 4.2.1 on 2023-06-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
