# Generated by Django 4.2.1 on 2023-07-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0006_post_created_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
